### ISSUE TITLE
"No text channels" part is not colorized

### ISSUE THREAD

**Issue by sitiom** [NYRI4/Discolored#4]
![No text channels](https://user-images.githubusercontent.com/56180050/111591525-881f5900-8802-11eb-820f-54a602f14657.png)

**Comment by NYRI4** [comment]
Thanks for reporting it, I'll fix it when I can

**Comment by NYRI4** [comment]
Should be colorized now ! :3

**Comment by sitiom** [comment]
Not working, but I see why.

**Comment by NYRI4** [comment]
why ? ^^

**Comment by sitiom** [comment]
https://github.com/NYRI4/Discolored/pull/5

**Comment by NYRI4** [comment]
Should be working now, thanks for your participation !

**Comment by sitiom** [comment]
Thanks, it's still not yet fixed on `support/discolored.user.css`.

**Comment by NYRI4** [comment]
There, sorry smh
